//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL3.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichLam
    {
        public Nullable<int> ID_NV { get; set; }
        public string CaLam { get; set; }
        public System.DateTime NgayLam { get; set; }
        public double Luong { get; set; }
<<<<<<< HEAD
=======
        public Nullable<double> Thuong { get; set; }
>>>>>>> 85abff1a886188270143c988969a866dbdb94731
    
        public virtual NhanVien NhanVien { get; set; }
    }
}
