//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL3.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiKhoan
    {
        public int ID_NV { get; set; }
        public string TaiKhoan1 { get; set; }
        public string MatKhau { get; set; }
        public string Loai_TK { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
    }
}
